-- =============================================================================
-- BRONZE LAYER – RAW / LANDING ZONE (CURRENTLY EMPTY IN PROTOTYPE)
-- =============================================================================
-- This schema represents the BRONZE layer of our data warehouse.
-- In a real production setup, it would store raw ingested data:
--   - IoT smart-meter streams (energy consumption per device/building)
--   - Raw weather API responses (JSON, CSV, etc.)
--   - Logs or external source files before any cleaning / transformation
--
-- For this prototype, the data is generated by Python scripts and loaded
-- directly into the SILVER layer (cleaned & modeled tables).
-- Therefore, we intentionally keep the BRONZE layer empty for now.
--
-- Later, when we connect real IoT devices or external feeds, we will:
--   - Create raw landing tables here (bronze.*)
--   - Ingest data as-is (schema-on-read)
--   - Build ETL/ELT jobs to move data from BRONZE -> SILVER -> GOLD.
--
-- No BRONZE tables are created at this stage on purpose.
-- =============================================================================

-- ✅ Create the BRONZE database (if not exists)
CREATE DATABASE bronze;

-- ✅ Switch to BRONZE database context
\c bronze;

-- (Schemas and tables will be added here later when raw ingestion is implemented)
