-- =============================================================================
-- SILVER LAYER – CLEANED / MODELED TABLES (PROTOTYPE)
-- =============================================================================
-- This database represents the SILVER layer of our data warehouse.
--
-- In this prototype:
--   - Data is generated by Python scripts (not from real IoT meters yet).
--   - We store already "clean" / structured tables in the SILVER layer.
--   - These tables will be the main source for:
--       * analytics & dashboards,
--       * ML training (energy + PV forecasting),
--       * GOLD-layer aggregates (daily/monthly KPIs).
-- =============================================================================

-- ✅ Create the SILVER database (if not exists)
CREATE DATABASE silver;

-- ✅ Switch to SILVER database context
\c silver;

-- =============================================================================
-- TABLE 1: ENERGY CONSUMPTION – HOURLY FACT TABLE (SILVER)
-- =============================================================================

CREATE TABLE IF NOT EXISTS energy_consumption_hourly (
    -- Time & building identification
    time_ts                TIMESTAMP      NOT NULL,  -- 'Time'
    building               VARCHAR(50)    NOT NULL,  -- 'Building'

    -- Season flags (one-hot encoding)
    winter_flag            SMALLINT       NOT NULL,  -- 'Winter' (0/1)
    spring_flag            SMALLINT       NOT NULL,  -- 'Spring' (0/1)
    summer_flag            SMALLINT       NOT NULL,  -- 'Summer' (0/1)
    fall_flag              SMALLINT       NOT NULL,  -- 'Fall'   (0/1)

    -- Weather-related features (REAL DATA from weather_forecast_hourly)
    outdoor_temp_c         NUMERIC(5,2),             -- 'Outdoor Temp (°C)'
    humidity_pct           NUMERIC(5,2),             -- 'Humidity (%)'
    cloud_cover_pct        NUMERIC(5,2),             -- 'Cloud Cover (%)'
    solar_radiation_w_m2   NUMERIC(8,2),             -- 'Solar Radiation (W/m²)'

    -- Temporal features
    hour_of_day            SMALLINT       NOT NULL,  -- 'Hour' (0–23)
    day_of_week            SMALLINT       NOT NULL,  -- 'DayOfWeek' (0=lundi…)
    month_num              SMALLINT       NOT NULL,  -- 'Month'
    day_of_year            SMALLINT       NOT NULL,  -- 'DayOfYear'
    is_weekend             SMALLINT       NOT NULL,  -- 'IsWeekend' (0/1)
    is_holiday             SMALLINT       NOT NULL,  -- 'IsHoliday' (0/1)
    is_peak_hour           SMALLINT       NOT NULL,  -- 'IsPeakHour' (0/1)

    -- Energy consumption components
    lighting_kw            NUMERIC(10,4),            -- 'Lighting [kW]'
    hvac_kw                NUMERIC(10,4),            -- 'HVAC [kW]'
    special_equipment_kw   NUMERIC(10,4),            -- 'Special Equipment [kW]'
    use_kw                 NUMERIC(10,4),            -- 'Use [kW]' (total load)

    -- Primary key: unique per timestamp and building
    CONSTRAINT pk_energy_silver PRIMARY KEY (time_ts, building)
);


CREATE INDEX IF NOT EXISTS idx_energy_time 
    ON energy_consumption_hourly(time_ts);

-- Index sur le building (filtres par bâtiment)
CREATE INDEX IF NOT EXISTS idx_energy_building 
    ON energy_consumption_hourly(building);

-- Index composite pour requêtes fréquentes
CREATE INDEX IF NOT EXISTS idx_energy_time_building 
    ON energy_consumption_hourly(time_ts, building);

-- Index sur les features temporelles (pour ML queries)
CREATE INDEX IF NOT EXISTS idx_energy_temporal 
    ON energy_consumption_hourly(month_num, day_of_week, hour_of_day);
-- Columnar + hash distribution by building for good analytical performance.
-- =============================================================================


-- =============================================================================
-- TABLE 2: WEATHER FORECAST – HOURLY (CASABLANCA, 3-DAY HORIZON)
-- =============================================================================

-- Ajoutez ceci dans databases/silver.sql

-- ============================================================================
-- Table: weather_forecast_hourly
-- Description: Prévisions météo horaires pour Casablanca
-- ============================================================================

DROP TABLE IF EXISTS weather_forecast_hourly CASCADE;

CREATE TABLE weather_forecast_hourly (
    -- Clé primaire: timestamp unique pour chaque prévision
    forecast_timestamp TIMESTAMP PRIMARY KEY,
    
    -- Date et heure séparées (pour faciliter les requêtes)
    forecast_date DATE NOT NULL,
    forecast_time TIME NOT NULL,
    
    -- Données météorologiques
    temperature_c NUMERIC(5,2),                      -- Température en °C
    humidity_pct NUMERIC(5,2),                       -- Humidité relative en %
    precipitation_mm NUMERIC(6,2),                   -- Précipitations en mm
    precipitation_probability_pct NUMERIC(5,2),      -- Probabilité de pluie en %
    weather_conditions VARCHAR(100),                 -- Description textuelle
    wind_speed_kmh NUMERIC(6,2),                     -- Vitesse du vent en km/h
    wind_direction_deg NUMERIC(5,2),                 -- Direction du vent en degrés
    pressure_hpa NUMERIC(7,2),                       -- Pression atmosphérique en hPa
    cloud_cover_pct NUMERIC(5,2),                    -- Couverture nuageuse en %
    solar_radiation_w_m2 NUMERIC(8,2),               -- ☀️ Rayonnement solaire en W/m²

    -- Métadonnées de suivi
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Index pour accélérer les requêtes
CREATE INDEX idx_weather_forecast_date ON weather_forecast_hourly(forecast_date);
CREATE INDEX idx_weather_forecast_timestamp ON weather_forecast_hourly(forecast_timestamp);
CREATE INDEX idx_weather_conditions ON weather_forecast_hourly(weather_conditions);


-- Index sur les conditions météo (pour filtrer par type de temps)


-- =============================================================================


-- END OF SILVER LAYER DEFINITION (for now).

