-- =============================================================================
-- SILVER LAYER – CLEANED / MODELED TABLES (PROTOTYPE)
-- =============================================================================
-- This database represents the SILVER layer of our data warehouse.
--
-- In this prototype:
--   - Data is generated by Python scripts (not from real IoT meters yet).
--   - We store already "clean" / structured tables in the SILVER layer.
--   - These tables will be the main source for:
--       * analytics & dashboards,
--       * ML training (energy + PV forecasting),
--       * GOLD-layer aggregates (daily/monthly KPIs).
-- =============================================================================

-- ✅ Create the SILVER database (if not exists)
CREATE DATABASE silver;

-- ✅ Switch to SILVER database context
\c silver;

-- =============================================================================
-- TABLE 1: ENERGY CONSUMPTION – HOURLY FACT TABLE (SILVER)
-- =============================================================================

CREATE TABLE energy_consumption_hourly (
    -- Time & building identification
    time_ts                TIMESTAMP      NOT NULL,  -- 'Time'
    building               VARCHAR(50)    NOT NULL,  -- 'Building'

    -- Season flags (one-hot encoding)
    winter_flag            SMALLINT       NOT NULL,  -- 'Winter' (0/1)
    spring_flag            SMALLINT       NOT NULL,  -- 'Spring' (0/1)
    summer_flag            SMALLINT       NOT NULL,  -- 'Summer' (0/1)
    fall_flag              SMALLINT       NOT NULL,  -- 'Fall'   (0/1)

    -- Weather-related features
    outdoor_temp_c         NUMERIC(5,2),             -- 'Outdoor Temp (°C)'
    humidity_pct           NUMERIC(5,2),             -- 'Humidity (%)'
    cloud_cover_pct        NUMERIC(5,2),             -- 'Cloud Cover (%)'
    solar_radiation_w_m2   NUMERIC(8,2),             -- 'Solar Radiation (W/m²)'

    -- Temporal features
    hour_of_day            SMALLINT       NOT NULL,  -- 'Hour' (0–23)
    day_of_week            SMALLINT       NOT NULL,  -- 'DayOfWeek' (0=lundi…)
    month_num              SMALLINT       NOT NULL,  -- 'Month'
    day_of_year            SMALLINT       NOT NULL,  -- 'DayOfYear'
    is_weekend             SMALLINT       NOT NULL,  -- 'IsWeekend' (0/1)
    is_holiday             SMALLINT       NOT NULL,  -- 'IsHoliday' (0/1)
    is_peak_hour           SMALLINT       NOT NULL,  -- 'IsPeakHour' (0/1)

    -- Energy consumption components
    lighting_kw            NUMERIC(10,4),            -- 'Lighting [kW]'
    hvac_kw                NUMERIC(10,4),            -- 'HVAC [kW]'
    special_equipment_kw   NUMERIC(10,4),            -- 'Special Equipment [kW]'
    use_kw                 NUMERIC(10,4),            -- 'Use [kW]' (total load)

    CONSTRAINT pk_energy_silver PRIMARY KEY (time_ts, building)
)
DISTRIBUTE BY HASH(building)
WITH (orientation = column, compression = low);

-- Columnar + hash distribution by building for good analytical performance.
-- =============================================================================


-- =============================================================================
-- TABLE 2: WEATHER FORECAST – HOURLY (CASABLANCA, 3-DAY HORIZON)
-- =============================================================================

CREATE TABLE weather_forecast_hourly (
    -- Date & time (local Casablanca time)
    forecast_date            DATE         NOT NULL,      -- 'Date'
    forecast_time_of_day     TIME         NOT NULL,      -- 'Heure' (HH:MM)

    -- Core weather metrics
    temperature_c            NUMERIC(5,2),              -- 'Temperature (°C)'
    humidity_pct             NUMERIC(5,2),              -- 'Humidité (%)'
    precipitation_mm         NUMERIC(6,3),              -- 'Précipitation (mm)'
    precipitation_prob_pct   NUMERIC(5,2),              -- 'Probabilité Pluie (%)'
    conditions_text          VARCHAR(100),              -- 'Conditions' (French description)
    wind_speed_kmh           NUMERIC(6,2),              -- 'Vitesse Vent (km/h)'
    wind_direction_deg       NUMERIC(5,1),              -- 'Direction Vent (°)'
    pressure_hpa             NUMERIC(7,2),              -- 'Pression (hPa)'
    cloud_cover_pct          NUMERIC(5,2),              -- 'Couverture Nuageuse (%)'

    -- Logical key: one forecast per date+hour
    CONSTRAINT pk_weather_forecast PRIMARY KEY (forecast_date, forecast_time_of_day)
)
DISTRIBUTE BY HASH(forecast_date)
WITH (orientation = column, compression = low);
-- =============================================================================

-- END OF SILVER LAYER DEFINITION (for now).
