-- =============================================================================
-- SILVER LAYER – CLEANED / MODELED TABLES (PROTOTYPE)
-- =============================================================================
-- This database represents the SILVER layer of our data warehouse.
--
-- In this prototype:
--   - Data is generated by Python scripts (not from real IoT meters yet).
--   - We store already "clean" / structured tables in the SILVER layer.
--   - These tables will be the main source for:
--       * analytics & dashboards,
--       * ML training (energy + PV forecasting),
--       * GOLD-layer aggregates (daily/monthly KPIs).
-- =============================================================================

-- ✅ Create the SILVER database (if not exists)
CREATE DATABASE silver;

-- ✅ Switch to SILVER database context
\c silver;

-- =============================================================================
-- TABLE 1: ENERGY CONSUMPTION – HOURLY FACT TABLE (SILVER)
-- =============================================================================

CREATE TABLE energy_consumption_hourly (
    -- Time & building identification
    time_ts                TIMESTAMP      NOT NULL,  -- 'Time'
    building               VARCHAR(50)    NOT NULL,  -- 'Building'

    -- Season flags (one-hot encoding)
    winter_flag            SMALLINT       NOT NULL,  -- 'Winter' (0/1)
    spring_flag            SMALLINT       NOT NULL,  -- 'Spring' (0/1)
    summer_flag            SMALLINT       NOT NULL,  -- 'Summer' (0/1)
    fall_flag              SMALLINT       NOT NULL,  -- 'Fall'   (0/1)

    -- Weather-related features
    outdoor_temp_c         NUMERIC(5,2),             -- 'Outdoor Temp (°C)'
    humidity_pct           NUMERIC(5,2),             -- 'Humidity (%)'
    cloud_cover_pct        NUMERIC(5,2),             -- 'Cloud Cover (%)'
    solar_radiation_w_m2   NUMERIC(8,2),             -- 'Solar Radiation (W/m²)'

    -- Temporal features
    hour_of_day            SMALLINT       NOT NULL,  -- 'Hour' (0–23)
    day_of_week            SMALLINT       NOT NULL,  -- 'DayOfWeek' (0=lundi…)
    month_num              SMALLINT       NOT NULL,  -- 'Month'
    day_of_year            SMALLINT       NOT NULL,  -- 'DayOfYear'
    is_weekend             SMALLINT       NOT NULL,  -- 'IsWeekend' (0/1)
    is_holiday             SMALLINT       NOT NULL,  -- 'IsHoliday' (0/1)
    is_peak_hour           SMALLINT       NOT NULL,  -- 'IsPeakHour' (0/1)

    -- Energy consumption components
    lighting_kw            NUMERIC(10,4),            -- 'Lighting [kW]'
    hvac_kw                NUMERIC(10,4),            -- 'HVAC [kW]'
    special_equipment_kw   NUMERIC(10,4),            -- 'Special Equipment [kW]'
    use_kw                 NUMERIC(10,4),            -- 'Use [kW]' (total load)

    CONSTRAINT pk_energy_silver PRIMARY KEY (time_ts, building)
)
DISTRIBUTE BY HASH(building)
WITH (orientation = column, compression = low);

-- Columnar + hash distribution by building for good analytical performance.
-- =============================================================================


-- =============================================================================
-- TABLE 2: WEATHER FORECAST – HOURLY (CASABLANCA, 3-DAY HORIZON)
-- =============================================================================

-- Ajoutez ceci dans databases/silver.sql

-- ============================================================================
-- Table: weather_forecast_hourly
-- Description: Prévisions météo horaires pour Casablanca
-- ============================================================================

CREATE TABLE IF NOT EXISTS weather_forecast_hourly (
    id SERIAL PRIMARY KEY,
    forecast_timestamp TIMESTAMP NOT NULL,
    forecast_date DATE NOT NULL,
    forecast_time TIME NOT NULL,
    temperature_c NUMERIC(5, 2),
    humidity_pct NUMERIC(5, 2),
    precipitation_mm NUMERIC(6, 2),
    precipitation_probability_pct NUMERIC(5, 2),
    weather_conditions VARCHAR(100),
    wind_speed_kmh NUMERIC(6, 2),
    wind_direction_deg NUMERIC(5, 2),
    pressure_hpa NUMERIC(7, 2),
    cloud_cover_pct NUMERIC(5, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index pour améliorer les performances
CREATE INDEX IF NOT EXISTS idx_weather_forecast_timestamp 
    ON weather_forecast_hourly(forecast_timestamp);

CREATE INDEX IF NOT EXISTS idx_weather_forecast_date 
    ON weather_forecast_hourly(forecast_date);

-- Commentaires
COMMENT ON TABLE weather_forecast_hourly IS 'Prévisions météo horaires récupérées depuis Open-Meteo API';
COMMENT ON COLUMN weather_forecast_hourly.forecast_timestamp IS 'Date et heure de la prévision';
COMMENT ON COLUMN weather_forecast_hourly.temperature_c IS 'Température en degrés Celsius';
COMMENT ON COLUMN weather_forecast_hourly.humidity_pct IS 'Humidité relative en pourcentage';
COMMENT ON COLUMN weather_forecast_hourly.precipitation_mm IS 'Précipitation en millimètres';
COMMENT ON COLUMN weather_forecast_hourly.precipitation_probability_pct IS 'Probabilité de pluie en pourcentage';
COMMENT ON COLUMN weather_forecast_hourly.weather_conditions IS 'Description des conditions météo';
COMMENT ON COLUMN weather_forecast_hourly.wind_speed_kmh IS 'Vitesse du vent en km/h';
COMMENT ON COLUMN weather_forecast_hourly.wind_direction_deg IS 'Direction du vent en degrés';
COMMENT ON COLUMN weather_forecast_hourly.pressure_hpa IS 'Pression atmosphérique en hPa';
COMMENT ON COLUMN weather_forecast_hourly.cloud_cover_pct IS 'Couverture nuageuse en pourcentage';
-- =============================================================================

-- END OF SILVER LAYER DEFINITION (for now).
